--박지성이 구매한 도서의 출판사와 같은 출판사에서 도서를 구매한 고객의 이름
SELECT C.NAME 
FROM BOOK B, CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID AND O.BOOKID = B.BOOKID    
    AND PUBLISHER IN(SELECT PUBLISHER
                     FROM CUSTOMER C1, BOOK B1, ORDERS O1
                     WHERE C1.CUSTID = O1.CUSTID
                     AND O1.BOOKID = B1.BOOKID
                     AND C1.NAME = '박지성')
                     AND NAME != '박지성';

--두 개 이상의 서로 다른 출판사에서 도서를 구매한 고객의 이름
SELECT NAME, COUNT(PUBLISHER)
FROM CUSTOMER C, ORDERS O, BOOK B 
WHERE  C.CUSTID = O.CUSTID AND O.BOOKID = B.BOOKID
GROUP BY NAME
HAVING COUNT(DISTINCT PUBLISHER) >= 2;

--위 문제 상관쿼리 버전
SELECT NAME
FROM CUSTOMER C1
WHERE 2 <= (SELECT COUNT(DISTINCT PUBLISHER)
            FROM CUSTOMER, ORDERS, BOOK
            WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
            AND ORDERS.BOOKID = BOOK.BOOKID
            AND CUSTOMER.NAME LIKE C1.NAME);

--전체 고객의 30% 이상이 구매한 도서
SELECT BOOKNAME, COUNT(BOOK.BOOKID)
FROM BOOK, ORDERS
WHERE BOOK.BOOKID = ORDERS.BOOKID
GROUP BY BOOKNAME
HAVING COUNT(ORDERS.BOOKID) >= 0.3*(SELECT COUNT(*) FROM CUSTOMER);

--위 문제 상관쿼리
SELECT BOOKNAME
FROM BOOK B1
WHERE (SELECT COUNT(ORDERS.BOOKID)
       FROM BOOK, ORDERS
       WHERE BOOK.BOOKID = ORDERS.BOOKID
        AND BOOK.BOOKID = B1.BOOKID) >= 0.3*(SELECT COUNT(*) FROM CUSTOMER);


--새로운 도서('스포츠 세계', '대한미디어', 10000원)이 마당서점에 입고되었다.
--삽입이 안될 경우 필요한 데이터가 더 있는지 찾아보자
INSERT INTO BOOK(BOOKID, BOOKNAME, PUBLISHER, PRICE)
        VALUES(11, '스포츠세계', '대한미디어', 10000);

--'삼성당'에서 출판한 도서를 삭제해야 한다.
DELETE FROM BOOK
WHERE PUBLISHER = '삼성당';

--'이상미디어'에서 출판한 도서를 삭제해야 한다. 삭제가 안 될 경우 원인을 생각해보자.
DELETE FROM BOOK
WHERE PUBLISHER = '이상미디어';

SELECT CONSTRAINT_NAME, TABLE_NAME, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'SYS_C007422';

--출판사'대한미디어'가 '대한출판사'로 이름을 바꾸었다.
UPDATE BOOK
SET PUBLISHER = '대한출판사'
WHERE PUBLISHER = '대한미디어';
