CREATE USER c##ERPproject IDENTIFIED BY tiger;

GRANT CREATE SESSION TO c##ERPproject;
GRANT CREATE TABLESPACE TO c##ERPproject;
GRANT CREATE TABLE TO c##ERPproject;
GRANT CREATE SEQUENCE TO c##ERPproject;
GRANT CREATE VIEW TO c##ERPproject;
GRANT CREATE SYNONYM TO c##ERPproject;

GRANT RESOURCE, CONNECT, UNLIMITED TABLESPACE TO c##ERPproject;

--사용자 삭제
DROP USER c##ERPsystem CASCADE;