CREATE TABLE USERS(
	ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    USERPROFILE VARCHAR2(200),
    USERROLE VARCHAR2(20),
    CREATEDATE TIMESTAMP
);

CREATE TABLE BOARD(
	ID NUMBER PRIMARY KEY,
    USERID NUMBER,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT CLOB,
    READCOUNT NUMBER DEFAULT 0,
    CREATEDATE TIMESTAMP,
    FOREIGN KEY (USERID) REFERENCES USERS (ID)
);

CREATE TABLE REPLY(
	ID NUMBER PRIMARY KEY,
    USERID NUMBER,
    BOARDID NUMBER,
    CONTENT VARCHAR2(300) NOT NULL,
    CREATEDATE TIMESTAMP,
    FOREIGN KEY (USERID) REFERENCES USERS (ID) ON DELETE SET NULL,
    FOREIGN KEY (BOARDID) REFERENCES BOARD (ID) ON DELETE CASCADE
);

CREATE SEQUENCE USERS_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE BOARD_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE REPLY_SEQ
START WITH 1 INCREMENT BY 1;

Drop table reply;
drop table board;
drop table users;