CREATE USER c##ssar IDENTIFIED BY bitc5600;
GRANT CREATE SESSION TO c##ssar;
GRANT CREATE TABLE TO c##ssar;
GRANT RESOURCE, CONNECT TO c##ssar;
GRANT CREATE SEQUENCE TO c##ssar;

GRANT UNLIMITED TABLESPACE TO c##ssar;
