CREATE USER c##madang IDENTIFIED BY c##madang DEFAULT TABLESPACE users TEMPORARY
TABLESPACE temp PROFILE DEFAULT;

GRANT CONNECT, RESOURCE TO c##madang;
GRANT CREATE VIEW, CREATE SYNONYM TO c##madang;