DESC EMP;

SELECT *
FROM EMP;

SELECT *
FROM EMP
WHERE SAL = 1250 AND COMM > 1000;

SELECT *
FROM EMP
WHERE ENAME = 'WARD';

SELECT *
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPTNO = 30;

SELECT DISTINCT JOB
FROM EMP;

SELECT DISTINCT DEPTNO "부서번호"
FROM EMP;

SELECT *
FROM STUDENT
WHERE HEIGHT >= 170;

SELECT *
FROM STUDENT
WHERE GRADE = 2 OR GRADE = 3;

SELECT *
FROM STUDENT
WHERE GRADE IN(2,3);

SELECT *
FROM EMP
WHERE JOB IN('SALESMAN', 'MANAGER', 'CLERK');

SELECT *
FROM EMP
WHERE SUBSTR(ENAME, 1, 1) = 'M';

SELECT *
FROM STUDENT
WHERE SUBSTR(BIRTHDAY, 3, 3) = '/02';

SELECT INSTR(TEL, '-') - INSTR(TEL, ')') - 1, TEL
FROM STUDENT;

SELECT ENAME, '$' || SAL 
FROM EMP;

SELECT NAME, SUBSTR(JUMIN, 3, 4) "BIRTHDAY",
             SUBSTR(JUMIN, 3, 4) -1 "BIRTHDAY - 1"
FROM STUDENT
WHERE DEPTNO1 = 101;

SELECT NAME, TEL, INSTR(TEL, ')')
FROM STUDENT
WHERE DEPTNO1 = 201;

SELECT NAME, TEL, SUBSTR(TEL, '3')
FROM STUDENT
WHERE DEPTNO1 = 101;

SELECT NAME, TEL, SUBSTR(TEL, 1, INSTR(TEL, ')')-1) "AREA CODE"
FROM STUDENT
WHERE DEPTNO1 = 201;

SELECT REPLACE('ABC', 'AB', 'F')
FROM DUAL;

SELECT RPAD(SUBSTR(JUMIN, 1, 7), 13, '*')
FROM STUDENT;

SELECT REPLACE(JUMIN, SUBSTR(JUMIN, 8), '******')
FROM STUDENT;

SELECT REPLACE(
                TEL,
                SUBSTR(TEL, 1, INSTR(TEL, ')') - 1),
                SUBSTR('***', 1, INSTR(TEL, ')') - 1)
                ) "오잉"
FROM STUDENT;

SELECT NAME, TEL, REPLACE(
                            TEL, 
                            SUBSTR(TEL, INSTR(TEL ,')') + 1, INSTR(TEL, '-') - INSTR(TEL, ')') -1),
                            SUBSTR('****', 1, INSTR(TEL, '-') - INSTR(TEL, ')') -1)
                        )
FROM STUDENT;

