CREATE TABLE MEMBER (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(50),
    GROUPTYPE VARCHAR2(20));
    
CREATE SEQUENCE MEMBER_SEQ
START WITH 1 INCREMENT BY 1;    